using UnityEngine;

public class CameraController : MonoBehaviour
{
    public Transform target; // Objeto a ser seguido pela c창mera
    public float smoothSpeed = 0.125f; // Velocidade suave de movimento da c창mera
    public Vector3 offset; // Dist창ncia entre a c창mera e o objeto seguido

    [SerializeField] Vector3 desiredPosition;

    private Vector3 velocity = Vector3.zero;

    private void FixedUpdate()
    {
        Vector3 desiredPosition = target.position + offset;
        Vector3 smoothedPosition = Vector3.SmoothDamp(transform.position, desiredPosition, ref velocity, smoothSpeed);
        transform.position = smoothedPosition;
    }
}
